---
name: GigaLink
version: 0.0.1
main: DerCooleVonDem\GigaLink\Main
api: 5.14.1
src-namespace-prefix: DerCooleVonDem\GigaLink
virions:
  - "DiscordBot"
permissions:
  gigalink.link:
    default: true
    description: "Allows the player to link their Discord account with their Minecraft account."

...
